services:
  postgres:
    image: postgres:16
    container_name: seasonal_japan_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata_seasonal_japan:/var/lib/postgresql/data

volumes:
  pgdata_seasonal_japan:
